spring.application.name=billeasy
spring.datasource.url=jdbc:mysql://localhost:3306/billeasy
spring.datasource.username=root
spring.datasource.password=LVMH
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 